[schroot] Don't fail if the LVM snapshot device does not exist

diff --git a/bin/schroot/setup/05lvm b/bin/schroot/setup/05lvm
--- a/bin/schroot/setup/05lvm
+++ b/bin/schroot/setup/05lvm
@@ -44,20 +44,29 @@ if [ "$CHROOT_TYPE" = "lvm-snapshot" ]; then
 
     elif [ $1 = "setup-stop" ]; then
 
-        # The lock needs to be dropped immediately before destroying
-        # the device.  There is a small race here, but the lock can't
-        # be dropped once the device has been removed.
-	if [ "$AUTH_VERBOSITY" = "verbose" ]; then
-	    echo "Removing device lock for $CHROOT_LVM_SNAPSHOT_DEVICE, owned by pid $PID"
-	fi
-        "$LIBEXEC_DIR/schroot-releaselock" \
-	    --device="$CHROOT_LVM_SNAPSHOT_DEVICE" \
-	    --pid=$PID || true
+	if [ -b "$CHROOT_LVM_SNAPSHOT_DEVICE" ]; then
+            # The lock needs to be dropped immediately before
+            # destroying the device.  There is a small race here, but
+            # the lock can't be dropped once the device has been
+            # removed.
+	    if [ "$AUTH_VERBOSITY" = "verbose" ]; then
+		echo "Removing device lock for $CHROOT_LVM_SNAPSHOT_DEVICE, owned by pid $PID"
+	    fi
+            "$LIBEXEC_DIR/schroot-releaselock" \
+		--device="$CHROOT_LVM_SNAPSHOT_DEVICE" \
+		--pid=$PID || true
 
-	if [ "$AUTH_VERBOSITY" = "verbose" ]; then
-	    lvremove $VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" || true
+	    if [ "$AUTH_VERBOSITY" = "verbose" ]; then
+		lvremove $VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" || true
+	    else
+		lvremove $VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" > /dev/null || true
+	    fi
 	else
-	    lvremove $VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" > /dev/null || true
+	    # The block device no longer exists, or was never created,
+	    # for example on lvcreate failure.
+	    if [ "$AUTH_VERBOSITY" = "verbose" ]; then
+		echo "W: $CHROOT_LVM_SNAPSHOT_DEVICE does not exist"
+	    fi
 	fi
 
     fi
