Replace tabs with spaces in all source code

diff --git a/etc/setup.d/05btrfs b/etc/setup.d/05btrfs
--- a/etc/setup.d/05btrfs
+++ b/etc/setup.d/05btrfs
@@ -27,40 +27,40 @@ if [ "$CHROOT_TYPE" = "btrfs-snapshot" ]; then
 
     if [ $STAGE = "setup-start" ]; then
 
-	if [ ! -d "$CHROOT_BTRFS_SOURCE_SUBVOLUME" ]; then
-	    fatal "Btrfs source subvolume directory '$CHROOT_BTRFS_SOURCE_SUBVOLUME' does not exist"
-	fi
-	if [ ! -d "$CHROOT_BTRFS_SNAPSHOT_DIRECTORY" ]; then
-	    fatal "Btrfs snapshot directory '$CHROOT_BTRFS_SNAPSHOT_DIRECTORY' does not exist"
-	fi
+        if [ ! -d "$CHROOT_BTRFS_SOURCE_SUBVOLUME" ]; then
+            fatal "Btrfs source subvolume directory '$CHROOT_BTRFS_SOURCE_SUBVOLUME' does not exist"
+        fi
+        if [ ! -d "$CHROOT_BTRFS_SNAPSHOT_DIRECTORY" ]; then
+            fatal "Btrfs snapshot directory '$CHROOT_BTRFS_SNAPSHOT_DIRECTORY' does not exist"
+        fi
 
-	info "Creating snapshot $CHROOT_BTRFS_SNAPSHOT_NAME from subvolume $CHROOT_BTRFS_SOURCE_SUBVOLUME"
+        info "Creating snapshot $CHROOT_BTRFS_SNAPSHOT_NAME from subvolume $CHROOT_BTRFS_SOURCE_SUBVOLUME"
 
-	if [ "$VERBOSE" = "verbose" ]; then
-	    btrfs subvolume snapshot "$CHROOT_BTRFS_SOURCE_SUBVOLUME" \
-		"$CHROOT_BTRFS_SNAPSHOT_NAME"
-	else
-	    btrfs subvolume snapshot "$CHROOT_BTRFS_SOURCE_SUBVOLUME" \
-		"$CHROOT_BTRFS_SNAPSHOT_NAME" > /dev/null
-	fi
+        if [ "$VERBOSE" = "verbose" ]; then
+            btrfs subvolume snapshot "$CHROOT_BTRFS_SOURCE_SUBVOLUME" \
+                "$CHROOT_BTRFS_SNAPSHOT_NAME"
+        else
+            btrfs subvolume snapshot "$CHROOT_BTRFS_SOURCE_SUBVOLUME" \
+                "$CHROOT_BTRFS_SNAPSHOT_NAME" > /dev/null
+        fi
 
     elif [ $STAGE = "setup-stop" ]; then
 
-	if [ -d "$CHROOT_BTRFS_SNAPSHOT_NAME" ]; then
+        if [ -d "$CHROOT_BTRFS_SNAPSHOT_NAME" ]; then
 
-	    info "Deleting snapshot $CHROOT_BTRFS_SNAPSHOT_NAME"
+            info "Deleting snapshot $CHROOT_BTRFS_SNAPSHOT_NAME"
 
-	    if [ "$VERBOSE" = "verbose" ]; then
-		btrfs subvolume delete "$CHROOT_BTRFS_SNAPSHOT_NAME" || true
-	    else
-		btrfs subvolume delete "$CHROOT_BTRFS_SNAPSHOT_NAME" > /dev/null || true
-	    fi
+            if [ "$VERBOSE" = "verbose" ]; then
+                btrfs subvolume delete "$CHROOT_BTRFS_SNAPSHOT_NAME" || true
+            else
+                btrfs subvolume delete "$CHROOT_BTRFS_SNAPSHOT_NAME" > /dev/null || true
+            fi
 
-	else
-	    # The block device no longer exists, or was never created,
-	    # for example on lvcreate failure.
-	    warn "$CHROOT_BTRFS_SNAPSHOT_NAME does not exist (it may have been removed previously)"
-	fi
+        else
+            # The block device no longer exists, or was never created,
+            # for example on lvcreate failure.
+            warn "$CHROOT_BTRFS_SNAPSHOT_NAME does not exist (it may have been removed previously)"
+        fi
 
     fi
 
diff --git a/etc/setup.d/05lvm b/etc/setup.d/05lvm
--- a/etc/setup.d/05lvm
+++ b/etc/setup.d/05lvm
@@ -31,40 +31,40 @@ if [ "$CHROOT_TYPE" = "lvm-snapshot" ]; then
 
     if [ $STAGE = "setup-start" ]; then
 
-	if [ ! "$DEVTYPE" "$CHROOT_DEVICE" ]; then
-	    fatal "Device '$CHROOT_DEVICE' does not exist"
-	fi
+        if [ ! "$DEVTYPE" "$CHROOT_DEVICE" ]; then
+            fatal "Device '$CHROOT_DEVICE' does not exist"
+        fi
 
-	if [ "$VERBOSE" = "verbose" ]; then
-	    lvcreate $LVM_VERBOSE --snapshot --name "$CHROOT_LVM_SNAPSHOT_NAME" \
-		"$CHROOT_DEVICE" $CHROOT_LVM_SNAPSHOT_OPTIONS
-	else
-	    lvcreate $LVM_VERBOSE --snapshot --name "$CHROOT_LVM_SNAPSHOT_NAME" \
-		"$CHROOT_DEVICE" $CHROOT_LVM_SNAPSHOT_OPTIONS > /dev/null
-	fi
+        if [ "$VERBOSE" = "verbose" ]; then
+            lvcreate $LVM_VERBOSE --snapshot --name "$CHROOT_LVM_SNAPSHOT_NAME" \
+                "$CHROOT_DEVICE" $CHROOT_LVM_SNAPSHOT_OPTIONS
+        else
+            lvcreate $LVM_VERBOSE --snapshot --name "$CHROOT_LVM_SNAPSHOT_NAME" \
+                "$CHROOT_DEVICE" $CHROOT_LVM_SNAPSHOT_OPTIONS > /dev/null
+        fi
 
     elif [ $STAGE = "setup-stop" ]; then
 
-	if [ "$DEVTYPE" "$CHROOT_LVM_SNAPSHOT_DEVICE" ]; then
+        if [ "$DEVTYPE" "$CHROOT_LVM_SNAPSHOT_DEVICE" ]; then
             # The lock needs to be dropped immediately before
             # destroying the device.  There is a small race here, but
             # the lock can't be dropped once the device has been
             # removed.
-	    info "Removing device lock for $CHROOT_LVM_SNAPSHOT_DEVICE, owned by pid $PID"
+            info "Removing device lock for $CHROOT_LVM_SNAPSHOT_DEVICE, owned by pid $PID"
             "$LIBEXEC_DIR/schroot-releaselock" \
-		--device="$CHROOT_LVM_SNAPSHOT_DEVICE" \
-		--pid=$PID || true
+                --device="$CHROOT_LVM_SNAPSHOT_DEVICE" \
+                --pid=$PID || true
 
-	    if [ "$VERBOSE" = "verbose" ]; then
-		lvremove $LVM_VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" || true
-	    else
-		lvremove $LVM_VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" > /dev/null || true
-	    fi
-	else
-	    # The block device no longer exists, or was never created,
-	    # for example on lvcreate failure.
-	    warn "$CHROOT_LVM_SNAPSHOT_DEVICE does not exist (it may have been removed previously)"
-	fi
+            if [ "$VERBOSE" = "verbose" ]; then
+                lvremove $LVM_VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" || true
+            else
+                lvremove $LVM_VERBOSE -f "$CHROOT_LVM_SNAPSHOT_DEVICE" > /dev/null || true
+            fi
+        else
+            # The block device no longer exists, or was never created,
+            # for example on lvcreate failure.
+            warn "$CHROOT_LVM_SNAPSHOT_DEVICE does not exist (it may have been removed previously)"
+        fi
 
     fi
 
diff --git a/etc/setup.d/05union b/etc/setup.d/05union
--- a/etc/setup.d/05union
+++ b/etc/setup.d/05union
@@ -26,41 +26,41 @@ set -e
 if [ -n "${CHROOT_UNION_TYPE}" ] && [ "${CHROOT_UNION_TYPE}" != 'none' ]; then
 
     if [ $STAGE = "setup-start" ]; then
-	mkdir "${CHROOT_UNION_OVERLAY_DIRECTORY}"
-	if [ ! -d "$CHROOT_UNION_OVERLAY_DIRECTORY" ]; then
-	    fatal "$CHROOT_UNION_OVERLAY_DIRECTORY does not exist, and could not be created"
-	fi
+        mkdir "${CHROOT_UNION_OVERLAY_DIRECTORY}"
+        if [ ! -d "$CHROOT_UNION_OVERLAY_DIRECTORY" ]; then
+            fatal "$CHROOT_UNION_OVERLAY_DIRECTORY does not exist, and could not be created"
+        fi
 
-	mkdir "${CHROOT_UNION_UNDERLAY_DIRECTORY}"
-	if [ ! -d "$CHROOT_UNION_UNDERLAY_DIRECTORY" ]; then
-	    fatal "$CHROOT_UNION_UNDERLAY_DIRECTORY does not exist, and could not be created"
-	fi
+        mkdir "${CHROOT_UNION_UNDERLAY_DIRECTORY}"
+        if [ ! -d "$CHROOT_UNION_UNDERLAY_DIRECTORY" ]; then
+            fatal "$CHROOT_UNION_UNDERLAY_DIRECTORY does not exist, and could not be created"
+        fi
 
     elif [ $STAGE = "setup-recover" ]; then
         if [ ! -d "${CHROOT_UNION_OVERLAY_DIRECTORY}" ]; then
-	    fatal "Missing overlay directory for session: can't recover"
+            fatal "Missing overlay directory for session: can't recover"
         fi
         if [ ! -d "${CHROOT_UNION_UNDERLAY_DIRECTORY}" ]; then
-	    fatal "Missing underlay directory for session: can't recover"
+            fatal "Missing underlay directory for session: can't recover"
         fi
 
     elif [ $STAGE = "setup-stop" ]; then
         if [ "$CHROOT_SESSION_PURGE" = "true" ]; then
-	    info "Purging $CHROOT_UNION_OVERLAY_DIRECTORY"
-	    if [ -d "${CHROOT_UNION_OVERLAY_DIRECTORY}" ]; then
-		rm -rf "${CHROOT_UNION_OVERLAY_DIRECTORY}"
-	    fi
+            info "Purging $CHROOT_UNION_OVERLAY_DIRECTORY"
+            if [ -d "${CHROOT_UNION_OVERLAY_DIRECTORY}" ]; then
+                rm -rf "${CHROOT_UNION_OVERLAY_DIRECTORY}"
+            fi
 
-	    # For safety, use rmdir rather than rm -rf in case
-	    # umount failed.
-	    info "Removing $CHROOT_UNION_UNDERLAY_DIRECTORY"
-	    if [ -d "${CHROOT_UNION_UNDERLAY_DIRECTORY}" ]; then
-		if ! rmdir "${CHROOT_UNION_UNDERLAY_DIRECTORY}"; then
-		    warn "Please unmount any filesystems and remove any files under $CHROOT_UNION_UNDERLAY_DIRECTORY"
-		    fatal "Failed to remove $CHROOT_UNION_UNDERLAY_DIRECTORY (directory not empty)."
-		fi
-	    fi
-	fi
+            # For safety, use rmdir rather than rm -rf in case
+            # umount failed.
+            info "Removing $CHROOT_UNION_UNDERLAY_DIRECTORY"
+            if [ -d "${CHROOT_UNION_UNDERLAY_DIRECTORY}" ]; then
+                if ! rmdir "${CHROOT_UNION_UNDERLAY_DIRECTORY}"; then
+                    warn "Please unmount any filesystems and remove any files under $CHROOT_UNION_UNDERLAY_DIRECTORY"
+                    fatal "Failed to remove $CHROOT_UNION_UNDERLAY_DIRECTORY (directory not empty)."
+                fi
+            fi
+        fi
     fi
 
 fi
diff --git a/etc/setup.d/10mount b/etc/setup.d/10mount
--- a/etc/setup.d/10mount
+++ b/etc/setup.d/10mount
@@ -33,13 +33,13 @@ do_mount()
     info "Mounting $2 on $3"
 
     if [ -h "$3" ]; then
-	fatal "$3 is a symbolic link, not usable as a mountpoint"
+        fatal "$3 is a symbolic link, not usable as a mountpoint"
     fi
     if [ ! -d "$3" ]; then
-	mkdir -p "$3"
+        mkdir -p "$3"
     fi
     if [ ! -d "$3" ]; then
-	fatal "$3 does not exist, and could not be created"
+        fatal "$3 does not exist, and could not be created"
     fi
 
     info "$MOUNT_VERBOSE $1 $2 $3"
@@ -51,43 +51,43 @@ do_mount()
 do_umount_all()
 {
     if [ -d "$1" ]; then
-	# Note that flock is used here to prevent races reading
-	# /proc/mounts, which on current (Linux 2.6.32) kernels is
-	# racy.  If other processes are mounting or unmounting
-	# filesystems as we read it, we can miss mount entries due to
-	# the file changing as we read it.  This needs fixing in the
-	# kernel, but an exclusive lock surrounding the
-	# schroot-listmounts invocation is a partial fix.  This
-	# prevents racing when multiple schroot processes are running.
-	# Note that this does not prevent the problem when programs
-	# other than schroot mount and unmount filesystems (since they
-	# don't create the lock).
-	if [ -e /var/lock/schroot ]; then
-	    if [ ! -d /var/lock/schroot ]; then
-		error "/var/lock/schroot is not a directory"
-		exit 1
-	    fi
-	else
-	    mkdir -m 0700 /var/lock/schroot
-	fi
+        # Note that flock is used here to prevent races reading
+        # /proc/mounts, which on current (Linux 2.6.32) kernels is
+        # racy.  If other processes are mounting or unmounting
+        # filesystems as we read it, we can miss mount entries due to
+        # the file changing as we read it.  This needs fixing in the
+        # kernel, but an exclusive lock surrounding the
+        # schroot-listmounts invocation is a partial fix.  This
+        # prevents racing when multiple schroot processes are running.
+        # Note that this does not prevent the problem when programs
+        # other than schroot mount and unmount filesystems (since they
+        # don't create the lock).
+        if [ -e /var/lock/schroot ]; then
+            if [ ! -d /var/lock/schroot ]; then
+                error "/var/lock/schroot is not a directory"
+                exit 1
+            fi
+        else
+            mkdir -m 0700 /var/lock/schroot
+        fi
 
-	if [ "$(stat -c "%u %g %a" /var/lock/schroot)" != "0 0 700" ]; then
-	    error "/var/lock/schroot is not owned by root:root, or lacks 0700 permissions"
-	    exit 1
-	fi
+        if [ "$(stat -c "%u %g %a" /var/lock/schroot)" != "0 0 700" ]; then
+            error "/var/lock/schroot is not owned by root:root, or lacks 0700 permissions"
+            exit 1
+        fi
 
-	( flock 9
-	    mounts="$("$LIBEXEC_DIR/schroot-listmounts" -m "$1")"
-	    if [ "x$mounts" != 'x' ]; then
-		echo "$mounts" |
-		while read mountloc; do
+        ( flock 9
+            mounts="$("$LIBEXEC_DIR/schroot-listmounts" -m "$1")"
+            if [ "x$mounts" != 'x' ]; then
+                echo "$mounts" |
+                while read mountloc; do
                     info "Unmounting $mountloc"
-		    umount "$mountloc" || exit 1
-		done || exit 1
-	    fi
-	) 9>"/var/lock/schroot/umount"
+                    umount "$mountloc" || exit 1
+                done || exit 1
+            fi
+        ) 9>"/var/lock/schroot/umount"
     else
-	warn "Mount location $1 no longer exists; skipping unmount"
+        warn "Mount location $1 no longer exists; skipping unmount"
     fi
 }
 
@@ -97,17 +97,17 @@ do_mount_fs_union()
 {
     # Prepare mount options (branch config) for union type
     if [ -z "$CHROOT_UNION_MOUNT_OPTIONS" ]; then
-	case $CHROOT_UNION_TYPE in
-	    unionfs)
-		CHROOT_UNION_MOUNT_OPTIONS="dirs=${CHROOT_UNION_OVERLAY_DIRECTORY}=rw,${CHROOT_UNION_UNDERLAY_DIRECTORY}=ro"
-		;;
-	    aufs)
-		CHROOT_UNION_MOUNT_OPTIONS="br:${CHROOT_UNION_OVERLAY_DIRECTORY}:${CHROOT_UNION_UNDERLAY_DIRECTORY}=ro"
-		;;
-	    overlayfs)
+        case $CHROOT_UNION_TYPE in
+            unionfs)
+                CHROOT_UNION_MOUNT_OPTIONS="dirs=${CHROOT_UNION_OVERLAY_DIRECTORY}=rw,${CHROOT_UNION_UNDERLAY_DIRECTORY}=ro"
+                ;;
+            aufs)
+                CHROOT_UNION_MOUNT_OPTIONS="br:${CHROOT_UNION_OVERLAY_DIRECTORY}:${CHROOT_UNION_UNDERLAY_DIRECTORY}=ro"
+                ;;
+            overlayfs)
                 CHROOT_UNION_MOUNT_OPTIONS="lowerdir=${CHROOT_UNION_UNDERLAY_DIRECTORY},upperdir=${CHROOT_UNION_OVERLAY_DIRECTORY}"
                 ;;
-	esac
+        esac
     fi
 
     info "Using '$CHROOT_UNION_TYPE' for filesystem union"
@@ -129,98 +129,98 @@ if [ "$CHROOT_TYPE" = "directory" ] \
     || [ "$CHROOT_TYPE" = "btrfs-snapshot" ]; then
 
     if [ "${CHROOT_UNION_TYPE:-none}" != "none" ]; then
-	CREATE_UNION="yes"
+        CREATE_UNION="yes"
     else
-	CREATE_UNION="no"
+        CREATE_UNION="no"
     fi
 
     if [ $STAGE = "setup-start" ] || [ $STAGE = "setup-recover" ]; then
 
-	case "$HOST_OS" in
-	    freebsd* | k*bsd*-gnu) :
-		BINDOPT="-t nullfs"
-		;;
-	    *):
-		BINDOPT="--bind"
-		;;
-	esac
+        case "$HOST_OS" in
+            freebsd* | k*bsd*-gnu) :
+                BINDOPT="-t nullfs"
+                ;;
+            *):
+                BINDOPT="--bind"
+                ;;
+        esac
 
-	if [ "$CHROOT_TYPE" = "directory" ]; then
-	    CHROOT_MOUNT_OPTIONS="$BINDOPT $CHROOT_MOUNT_OPTIONS"
-	    CHROOT_MOUNT_DEVICE="$CHROOT_DIRECTORY"
-	    if [ ! -d "$CHROOT_DIRECTORY" ]; then
-		fatal "Directory '$CHROOT_DIRECTORY' does not exist"
-	    fi
-	elif [ "$CHROOT_TYPE" = "file" ]; then
-	    CHROOT_MOUNT_OPTIONS="$BINDOPT $CHROOT_MOUNT_OPTIONS"
-	    CHROOT_MOUNT_DEVICE="${CHROOT_FILE_UNPACK_DIR}/${SESSION_ID}"
-	elif [ "$CHROOT_TYPE" = "block-device" ]; then
-	    if [ ! "$DEVTYPE" "$CHROOT_DEVICE" ]; then
-		fatal "Device '$CHROOT_DEVICE' does not exist"
-	    fi
-	elif [ "$CHROOT_TYPE" = "btrfs-snapshot" ]; then
-	    CHROOT_MOUNT_OPTIONS="$BINDOPT $CHROOT_MOUNT_OPTIONS"
-	    CHROOT_MOUNT_DEVICE="$CHROOT_BTRFS_SNAPSHOT_NAME"
-	elif [ "$CHROOT_TYPE" = "loopback" ]; then
-	    if [ ! -f "$CHROOT_FILE" ]; then
-	    	fatal "File '$CHROOT_FILE' does not exist"
-	    fi
+        if [ "$CHROOT_TYPE" = "directory" ]; then
+            CHROOT_MOUNT_OPTIONS="$BINDOPT $CHROOT_MOUNT_OPTIONS"
+            CHROOT_MOUNT_DEVICE="$CHROOT_DIRECTORY"
+            if [ ! -d "$CHROOT_DIRECTORY" ]; then
+                fatal "Directory '$CHROOT_DIRECTORY' does not exist"
+            fi
+        elif [ "$CHROOT_TYPE" = "file" ]; then
+            CHROOT_MOUNT_OPTIONS="$BINDOPT $CHROOT_MOUNT_OPTIONS"
+            CHROOT_MOUNT_DEVICE="${CHROOT_FILE_UNPACK_DIR}/${SESSION_ID}"
+        elif [ "$CHROOT_TYPE" = "block-device" ]; then
+            if [ ! "$DEVTYPE" "$CHROOT_DEVICE" ]; then
+                fatal "Device '$CHROOT_DEVICE' does not exist"
+            fi
+        elif [ "$CHROOT_TYPE" = "btrfs-snapshot" ]; then
+            CHROOT_MOUNT_OPTIONS="$BINDOPT $CHROOT_MOUNT_OPTIONS"
+            CHROOT_MOUNT_DEVICE="$CHROOT_BTRFS_SNAPSHOT_NAME"
+        elif [ "$CHROOT_TYPE" = "loopback" ]; then
+            if [ ! -f "$CHROOT_FILE" ]; then
+                    fatal "File '$CHROOT_FILE' does not exist"
+            fi
 
-	    case "$HOST_OS" in
-		freebsd* | k*bsd*-gnu):
-		    LOOP_DEVICE="/dev/$(/sbin/mdconfig -a -t vnode -f "$CHROOT_FILE")"
-		    CHROOT_MOUNT_DEVICE="$LOOP_DEVICE"
-		    ;;
-		*):
-		    LOOP_DEVICE="$(/sbin/losetup -j "$CHROOT_FILE" | sed -e 's/:.*$//')"
-		    if [ -z "$LOOP_DEVICE" ]; then
-			CHROOT_MOUNT_DEVICE="$CHROOT_FILE"
-			CHROOT_MOUNT_OPTIONS="-o loop $CHROOT_MOUNT_OPTIONS"
-		    else
-			CHROOT_MOUNT_DEVICE="$LOOP_DEVICE"
-		    fi
-		    ;;
-	    esac
-	fi
+            case "$HOST_OS" in
+                freebsd* | k*bsd*-gnu):
+                    LOOP_DEVICE="/dev/$(/sbin/mdconfig -a -t vnode -f "$CHROOT_FILE")"
+                    CHROOT_MOUNT_DEVICE="$LOOP_DEVICE"
+                    ;;
+                *):
+                    LOOP_DEVICE="$(/sbin/losetup -j "$CHROOT_FILE" | sed -e 's/:.*$//')"
+                    if [ -z "$LOOP_DEVICE" ]; then
+                        CHROOT_MOUNT_DEVICE="$CHROOT_FILE"
+                        CHROOT_MOUNT_OPTIONS="-o loop $CHROOT_MOUNT_OPTIONS"
+                    else
+                        CHROOT_MOUNT_DEVICE="$LOOP_DEVICE"
+                    fi
+                    ;;
+            esac
+        fi
 
         if [ ! -d "$CHROOT_MOUNT_LOCATION" ]; then
-	    mkdir -p "$CHROOT_MOUNT_LOCATION"
+            mkdir -p "$CHROOT_MOUNT_LOCATION"
         fi
-	if [ ! -d "$CHROOT_MOUNT_LOCATION" ]; then
-	    fatal "$CHROOT_MOUNT_LOCATION does not exist, and could not be created"
-	fi
+        if [ ! -d "$CHROOT_MOUNT_LOCATION" ]; then
+            fatal "$CHROOT_MOUNT_LOCATION does not exist, and could not be created"
+        fi
 
-	# If recovering, we want to remount all filesystems to ensure
-	# a sane state.
-	if [ $STAGE = "setup-recover" ]; then
-	    if [ "$CREATE_UNION" = "yes" ]; then
-		do_umount_all "$CHROOT_UNION_UNDERLAY_DIRECTORY"
-	    fi
-	    do_umount_all "$CHROOT_MOUNT_LOCATION"
-	fi
+        # If recovering, we want to remount all filesystems to ensure
+        # a sane state.
+        if [ $STAGE = "setup-recover" ]; then
+            if [ "$CREATE_UNION" = "yes" ]; then
+                do_umount_all "$CHROOT_UNION_UNDERLAY_DIRECTORY"
+            fi
+            do_umount_all "$CHROOT_MOUNT_LOCATION"
+        fi
 
-	if [ "$CREATE_UNION" = "yes" ]; then
-	    do_mount "$CHROOT_MOUNT_OPTIONS" "$CHROOT_MOUNT_DEVICE" "$CHROOT_UNION_UNDERLAY_DIRECTORY"
-	    do_mount_fs_union "$CHROOT_MOUNT_LOCATION"
-	else
-	    do_mount "$CHROOT_MOUNT_OPTIONS" "$CHROOT_MOUNT_DEVICE" "$CHROOT_MOUNT_LOCATION"
-	fi
+        if [ "$CREATE_UNION" = "yes" ]; then
+            do_mount "$CHROOT_MOUNT_OPTIONS" "$CHROOT_MOUNT_DEVICE" "$CHROOT_UNION_UNDERLAY_DIRECTORY"
+            do_mount_fs_union "$CHROOT_MOUNT_LOCATION"
+        else
+            do_mount "$CHROOT_MOUNT_OPTIONS" "$CHROOT_MOUNT_DEVICE" "$CHROOT_MOUNT_LOCATION"
+        fi
 
     elif [ $STAGE = "setup-stop" ]; then
 
-	do_umount_all "$CHROOT_MOUNT_LOCATION"
-	if [ "$CREATE_UNION" = "yes" ]; then
-	    do_umount_all "$CHROOT_UNION_UNDERLAY_DIRECTORY"
-	fi
+        do_umount_all "$CHROOT_MOUNT_LOCATION"
+        if [ "$CREATE_UNION" = "yes" ]; then
+            do_umount_all "$CHROOT_UNION_UNDERLAY_DIRECTORY"
+        fi
 
-	# Purge mount location.
-	# The contents of file chroots are purged separately, because
-	# we might want to repack the contents.
-	if echo "$CHROOT_MOUNT_LOCATION" | grep -q "^$MOUNT_DIR/"; then
-	    if [ -d "$CHROOT_MOUNT_LOCATION" ]; then
-		rmdir "$CHROOT_MOUNT_LOCATION"
-	    fi
-	fi
+        # Purge mount location.
+        # The contents of file chroots are purged separately, because
+        # we might want to repack the contents.
+        if echo "$CHROOT_MOUNT_LOCATION" | grep -q "^$MOUNT_DIR/"; then
+            if [ -d "$CHROOT_MOUNT_LOCATION" ]; then
+                rmdir "$CHROOT_MOUNT_LOCATION"
+            fi
+        fi
 
     fi
 
@@ -230,12 +230,12 @@ fi
 if [ $STAGE = "setup-start" ] || [ $STAGE = "setup-recover" ]; then
 
     if [ -n "$SETUP_FSTAB" ]; then
-	if [ -f "$SETUP_FSTAB" ]; then
-	    "$LIBEXEC_DIR/schroot-mount" $MOUNT_VERBOSE \
-		-f "$SETUP_FSTAB" -m "$CHROOT_PATH"
-	else
-	    fatal "setup_fstab file '$SETUP_FSTAB' does not exist"
-	fi
+        if [ -f "$SETUP_FSTAB" ]; then
+            "$LIBEXEC_DIR/schroot-mount" $MOUNT_VERBOSE \
+                -f "$SETUP_FSTAB" -m "$CHROOT_PATH"
+        else
+            fatal "setup_fstab file '$SETUP_FSTAB' does not exist"
+        fi
     fi
 
 fi
diff --git a/etc/setup.d/20copyfiles b/etc/setup.d/20copyfiles
--- a/etc/setup.d/20copyfiles
+++ b/etc/setup.d/20copyfiles
@@ -34,64 +34,64 @@ copy_file()
 {
     if [ -e "$1" ]; then
 
-	COPY="true"
+        COPY="true"
 
-	if [ -e "$2" ]; then
+        if [ -e "$2" ]; then
 
             # Device and inode
-	    da=$(/usr/bin/stat --format="%d %i" "$1")
-	    # This one can fail since it might not exist yet
-	    db=$(/usr/bin/stat --format="%d %i" "$2" 2>/dev/null || :)
+            da=$(/usr/bin/stat --format="%d %i" "$1")
+            # This one can fail since it might not exist yet
+            db=$(/usr/bin/stat --format="%d %i" "$2" 2>/dev/null || :)
 
-	    if [ "$da" = "$db" ]; then
-		COPY="false"
-	    elif [ -L "$2" ]; then
-		# Copy if destination is a symlink
-		:
-	    elif [ -f "$1" ] && [ -f "$2" ]; then
+            if [ "$da" = "$db" ]; then
+                COPY="false"
+            elif [ -L "$2" ]; then
+                # Copy if destination is a symlink
+                :
+            elif [ -f "$1" ] && [ -f "$2" ]; then
                 # Content
-		ca=$(/usr/bin/md5sum "$1" | sed -e 's/\(^[0-9a-f][0-9a-f]*\).*$/\1/')
-		cb=$(/usr/bin/md5sum "$2" 2>/dev/null || :)
-		cb=$(echo "$cb" | sed -e 's/\(^[0-9a-f][0-9a-f]*\).*$/\1/')
-	        # Copy only if file contents differ
-		if [ "$ca" = "$cb" ]; then
-		    COPY="false"
-		fi
-	    fi
-	fi
+                ca=$(/usr/bin/md5sum "$1" | sed -e 's/\(^[0-9a-f][0-9a-f]*\).*$/\1/')
+                cb=$(/usr/bin/md5sum "$2" 2>/dev/null || :)
+                cb=$(echo "$cb" | sed -e 's/\(^[0-9a-f][0-9a-f]*\).*$/\1/')
+                # Copy only if file contents differ
+                if [ "$ca" = "$cb" ]; then
+                    COPY="false"
+                fi
+            fi
+        fi
 
-	# Copy only if files are different
-	if [ "$COPY" = "true" ]; then
-	    if [ -f "$1" ]; then
-		cp --preserve=all $CP_VERBOSE "$1" "$2"
-	    else
-	        # Copy non-regular file directly
-		cp -a $CP_VERBOSE "$1" "$2"
-	    fi
-	fi
+        # Copy only if files are different
+        if [ "$COPY" = "true" ]; then
+            if [ -f "$1" ]; then
+                cp --preserve=all $CP_VERBOSE "$1" "$2"
+            else
+                # Copy non-regular file directly
+                cp -a $CP_VERBOSE "$1" "$2"
+            fi
+        fi
 
     else
-	fatal "Not copying nonexistent file: $file"
+        fatal "Not copying nonexistent file: $file"
     fi
 }
 
 if [ $STAGE = "setup-start" ] || [ $STAGE = "setup-recover" ]; then
 
     if [ -n "$SETUP_COPYFILES" ]; then
-	if [ -f "$SETUP_COPYFILES" ]; then
-	    while read file; do
-		if echo "$file" | egrep -q '^(#|$)' ; then
-		    continue
-		fi
-		if echo "$file" | grep -q '^/'; then
-		    copy_file "$file" "${CHROOT_PATH}$file"
-		else
-		    warn "Not copying file with relative path: $file"
-		fi
-	    done < "$SETUP_COPYFILES"
-	else
-	    fatal "copyfiles file '$SETUP_COPYFILES' does not exist"
-	fi
+        if [ -f "$SETUP_COPYFILES" ]; then
+            while read file; do
+                if echo "$file" | egrep -q '^(#|$)' ; then
+                    continue
+                fi
+                if echo "$file" | grep -q '^/'; then
+                    copy_file "$file" "${CHROOT_PATH}$file"
+                else
+                    warn "Not copying file with relative path: $file"
+                fi
+            done < "$SETUP_COPYFILES"
+        else
+            fatal "copyfiles file '$SETUP_COPYFILES' does not exist"
+        fi
     fi
 
 fi
diff --git a/etc/setup.d/20nssdatabases b/etc/setup.d/20nssdatabases
--- a/etc/setup.d/20nssdatabases
+++ b/etc/setup.d/20nssdatabases
@@ -35,30 +35,30 @@ dup_nss()
 if [ $STAGE = "setup-start" ] || [ $STAGE = "setup-recover" ]; then
 
     if [ -n "$SETUP_NSSDATABASES" ]; then
-	if [ -f "$SETUP_NSSDATABASES" ]; then
-	    while read db; do
-		if echo "$db" | egrep -q '^(#|$)' ; then
-		    continue
-		fi
+        if [ -f "$SETUP_NSSDATABASES" ]; then
+            while read db; do
+                if echo "$db" | egrep -q '^(#|$)' ; then
+                    continue
+                fi
 
                 # Device and inode
-		dr=$(/usr/bin/stat --format="%d %i" "/etc/$db")
-		# This one can fail since it might not exist yet
-		dc=$(/usr/bin/stat --format="%d %i" "${CHROOT_PATH}/etc/$db" 2>/dev/null || :)
+                dr=$(/usr/bin/stat --format="%d %i" "/etc/$db")
+                # This one can fail since it might not exist yet
+                dc=$(/usr/bin/stat --format="%d %i" "${CHROOT_PATH}/etc/$db" 2>/dev/null || :)
 
-	        # If the database inside and outside the chroot is the
-	        # same, it's very likely that dup_nss would blank the
-	        # database, so skip it.
-		if [ "$dr" = "$dc" ]; then
-		    warn "$db files '/etc/$db' and '${CHROOT_PATH}/etc/$db' are the same file; skipping"
-		    continue;
-		fi
+                # If the database inside and outside the chroot is the
+                # same, it's very likely that dup_nss would blank the
+                # database, so skip it.
+                if [ "$dr" = "$dc" ]; then
+                    warn "$db files '/etc/$db' and '${CHROOT_PATH}/etc/$db' are the same file; skipping"
+                    continue;
+                fi
 
-		dup_nss "$db" "${CHROOT_PATH}/etc/$db"
-	    done < "$SETUP_NSSDATABASES"
-	else
-	    fatal "nssdatabases file '$SETUP_NSSDATABASES' does not exist"
-	fi
+                dup_nss "$db" "${CHROOT_PATH}/etc/$db"
+            done < "$SETUP_NSSDATABASES"
+        else
+            fatal "nssdatabases file '$SETUP_NSSDATABASES' does not exist"
+        fi
     fi
 
 fi
