* schroot/setup/10mount (do_mount) : Create directories for   mounting filesystems onto if they don't exist.

diff --git a/schroot/setup/10mount b/schroot/setup/10mount
--- a/schroot/setup/10mount
+++ b/schroot/setup/10mount
@@ -11,6 +11,15 @@ do_mount()
     if [ "$AUTH_VERBOSITY" = "verbose" ]; then
 	echo "Mounting $2 on $3"
     fi
+
+    if [ ! -d "$3" ]; then
+	mkdir -p "$3"
+    fi
+    if [ ! -d "$3" ]; then
+	echo "$3 does not exist, and could not be created"
+	exit 1
+    fi
+
     mount $VERBOSE $1 "$2" "$3"
 }
 
